name: Auto Label PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Label PR based on file changes
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.PAT_TOKEN }}
