name: Process Merge Queue

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once every 24 hours at midnight UTC

jobs:
  process-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Process Merge Queue
        run: |
          if [ ! -f .github/merge-queue.txt ]; then
            echo "Merge queue file does not exist. Exiting..."
            exit 0
          fi
          QUEUE=$(cat .github/merge-queue.txt)
          if [[ "$QUEUE" != "" ]]; then
            FIRST_PR=$(head -n 1 .github/merge-queue.txt)
            echo "Processing PR #$FIRST_PR"
            git fetch origin pull/$FIRST_PR/head:pr-$FIRST_PR
            git checkout main
            git merge --no-ff pr-$FIRST_PR
            git push origin master
            # Remove the first line from the queue file
            sed -i '' 1d .github/merge-queue.txt || sed -i '1d' .github/merge-queue.txt
          else
            echo "No PRs in the queue."
          fi
