name: Enqueue PR for Merge

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

jobs:
  enqueue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Add PR to Merge Queue if Ready to Merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Convert the PR labels JSON to a string for easier searching
          PR_LABELS="${{ toJson(github.event.pull_request.labels) }}"
          echo "PR Labels: $PR_LABELS"

          # Check if the "Ready to Merge" label is present
          if echo "$PR_LABELS" | grep -q '"name": *"Ready to Merge"'; then
            echo "PR is marked as 'Ready to Merge'. Adding to merge queue..."
            echo "${{ github.event.pull_request.number }}" >> .github/merge-queue.txt
          else
            echo "PR is not marked as 'Ready to Merge'. Skipping queue addition."
            exit 0
          fi

      - name: Update PR Labels
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Attempt to remove the "Ready to Merge" label
            try {
              await github.issues.removeLabel({
                owner,
                repo,
                issue_number: prNumber,
                name: "Ready to Merge"
              });
              console.log("Removed 'Ready to Merge' label.");
            } catch (error) {
              console.log("Could not remove 'Ready to Merge' label. It may not exist.");
            }
            
            // Add the "Merge Queued" label
            await github.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: ["Merge Queued"]
            });
            console.log("Added 'Merge Queued' label.");
