name: Unity Post-Merge Build

on:
  push:
    branches:
      - master  # Runs a full build when a PR is merged into 'master'

jobs:
  build:
    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - iOS
          - Android
          - WebGL
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@main

      - name: Build for ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Delete Old GitHub Release
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: 'latest'
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true 

      - name: Delete Old Git Tag (If Exists)
        run: |
          git tag -d latest || true
          git push origin --delete latest || true
        continue-on-error: true  

      - name: Create or Update "Latest" Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          release_name: "Latest Unity Build"
          body: "This release is automatically updated with the latest successful Unity build."
          draft: false
          prerelease: false
          files: build/*
          token: ${{ secrets.GITHUB_TOKEN }}
